name: marble
channels:
  - conda-forge
  - cdat
  - defaults

dependencies:
  - python=3.11.7
  - pip=24.0
  # xarray includes: pandas
  - xarray=2024.1.1
  - netcdf4=1.6.5
  - pydap=3.4.0
  # birdy incudes: owslib, lxml
  - birdy=0.8.4
  - h5netcdf=1.3.0
  - matplotlib=3.8.2
  - cartopy=0.22.0
  - bokeh=3.3.4
  - dask=2024.2.0
  - flox=0.9.2
  - cf_xarray=0.8.9
  - cfgrib=0.9.10.4
  - yq=3.2.3
  - jsonschema=4.21.1
  - nbval=0.10.0
  - jupyterlab=3.6.7
  # Jupyter plugins-------------------------------------------------
  # https:://github.com/jupyterhub/jupyter-server-proxy
  - jupyter-server-proxy=4.1.0
  # https://github.com/dask/dask-labextension
  - dask-labextension=6.2.0
  - jupyter_bokeh>=3.0.0
  - pytest=8.0.0
  - nc-time-axis=1.4.1
  - aiohttp=3.9.3
  - scikit-image=0.22.0
  - ipyleaflet=0.18.2
  - ipywidgets=8.1.2
  - regionmask=0.11.0
  - siphon=0.9
  - gcsfs=2024.2.0
  - zarr=2.16.1
  - paramiko=3.4.0
  - urlpath=1.2.0
  - seaborn=0.13.2
  - statsmodels=0.14.1
  - pre-commit=3.6.1
  # https://github.com/roocs/clisops
  - clisops=0.12.2
  # Universal Regridder for Geospatial Data
  # https://github.com/pangeo-data/xESMF
  # xesmf imcludes: numba, esmpy
  - xesmf=0.8.2
  # Sensitivity Analysis Library
  # https://anaconda.org/conda-forge/salib, https://github.com/SALib/SALib
  - salib=1.4.7
  - nodejs=20.9.0
  - esgf-pyclient=0.3.1
  - geopy=2.4.1
  - xlrd=2.0.1
  - pillow=10.2.0
  - openpyxl=3.1.2
  - pyogrio=0.7.2
  - intake=2.0.1
  - intake-esm=2023.11.10
  - intake-xarray=0.7.0
  - intake-geopandas=0.4.0
  - intake-thredds=2022.8.19
  - pip:
    - requests-magpie==0.2.0
    - pystac-client==0.7.5
    - xncml==0.4.0
    # https://pypi.org/project/fstd2nc/
    # Converts RPN standard files (from Environment Canada) to netCDF files.
    - fstd2nc==0.20231105.1
    - marble-client==1.1.1

