name: marble
channels:
  - conda-forge
  - cdat
  - defaults

dependencies:
  - python=3.11.7
  - pip
  # xarray includes: pandas
  - xarray
  - netcdf4
  - pydap
  # birdy incudes: owslib, lxml
  - birdy
  - h5netcdf
  - matplotlib
  - cartopy
  - bokeh
  - dask
  - flox
  - cf_xarray
  - cfgrib
  - yq
  - jsonschema
  - nbval
  - jupyterlab=3.6.7
  # Jupyter plugins-------------------------------------------------
  # https:://github.com/jupyterhub/jupyter-server-proxy
  - jupyter-server-proxy
  # https://github.com/dask/dask-labextension
  - dask-labextension
  - jupyter_bokeh=3.0.7
  - pytest
  - nc-time-axis
  - aiohttp
  - scikit-image
  - ipyleaflet
  - ipywidgets
  - regionmask
  - siphon
  - gcsfs
  - zarr
  - s3fs
  - paramiko
  - urlpath
  - seaborn
  - statsmodels
  - pre-commit
  # https://github.com/roocs/clisops
  - clisops
  # Universal Regridder for Geospatial Data
  # https://github.com/pangeo-data/xESMF
  # xesmf imcludes: numba, esmpy
  - xesmf
  # Sensitivity Analysis Library
  # https://anaconda.org/conda-forge/salib, https://github.com/SALib/SALib
  - salib
  - nodejs
  - esgf-pyclient
  - geopy
  - pip:
    - requests-magpie
    - pystac-client
    - xncml

# Need:


# Maybe good to have:
  # - intake
  # - intake-esm
  # - intake-xarray
  # - intake-geopandas
  # - intake-thredds
  # - jupyter (what good is it here?)
  # - jupyter_bokeh (is it needed?)
